---
    # First, check if the SSH config file exists
    - name: Backup the existing SSH configuration file
      stat: path=/etc/ssh/sshd_config
      register: config_status

    # Backup the SSH config file (if it exists)
    - name: Copy the sshd_config to sshd_config.orig
      copy: remote_src=True
            src=/etc/ssh/sshd_config
            dest=/etc/ssh/sshd_config.orig

    # Disable root logins
    - name: Change PermitRootLogin to 'no'
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp='^#PermitRootLogin'
                  line='PermitRootLogin no'
                  state=present

    # Allow the Ansible user ('ansibleuser') to log in via SSH
    - name: Add 'AllowUsers' to sshd_config
      lineinfile: dest=/etc/ssh/sshd_config
                  line='AllowUsers ansibleuser'
                  state=present

      notify:
        - restart_sshd
